287 lines (275 sloc)  8.19 KB

title: Práctica 1 - Configuración de máquina virtual en el IaaS
description: Creación y configuración de mv en el entorno IaaS de la Universidad de La Laguna.
theme: slate
